# Documentazione generale kernel EvangelionNG 2.0.7.s
:toc: left
:last-update-label!:

include::../common/homelink.adoc[]

About
-----
Questa sezione descrive le caratteristiche generali del kernel

Struttura generale
------------------
Evangelion è un kernel prevalentemente di tipo micro, ciò significa che i servizi forniti sono dipartiti tra più entità.

Nel Kernel Space si trovano: 

- <<EvaLoader, EvaLoader>> 

- <<EvangelionNG, EvangelionNG>>.

A livello userspace, i moduli del kernel eseguiti come applicazioni prendono il nome di `server` i cui eseguibili sono contenuti nella cartella `/sys/svs/`:

- <<Spawner, Spawner>>

- <<Ps2Driver, Ps2Driver>>

- <<VesaDriver, VesaDriver>>

- <<TimeDriver, TimeDriver>>

EvaLoader
---------
`EvaLoader` é il primo dei componenti del kernel.
Viene lanciato dal bootloader GRUB e contiene la struttura dati `MultiBoot`, fondamentale per il passaggio di dati d'ambiente dal bootloader.
EvaLoader una volta in esecuzione provvede alla paginazione la memoria fin dove l'indirizzamento a `32bit` permette di arrivare (2^32 = 4GB), finita la paginazione lancia l'eseguibile di <<EvangelionNG, EvangelionNG>>, il core del kernel. Una volta che EvangelionNG entra in esecuzione EvaLoader viene deallocato

EvangelionNG
------------
`EvangelionNG` è il nucleo del kernel, è responsabile della schedulazione dei <<threads#, thread>> e dei <<threads#, processi>> e della loro comunicazione, della gestione della <<memory#, memoria>> e del <<ramdisk-format#, ramdisk>>.
Gestisce il processore e l' `SMP`.
Ed é inoltre responsabile della gestione delle chiamate di sistema fatte dalle applicazioni userspace.

Spawner
-------
`Spawner` é l'unico server di livello kernel (<<threads#SecurityLevels,livelli di sicurezza dei task>>), viene lanciato da init e rimane in esecuzione fino allo spegnimento di MeetiX OS.
Lo Spawner è responsabile della configurazione e dell'avvio delle applicazioni da userspace.
Per lanciare un applicazione su MeetiX OS è necessario usare la serie di chiamate di sistema <<libapi#5Spawn, Spawn()>>.

Ps2Driver
---------
`Ps2Driver` é un server di livello driver, provvede, tramite messaggi e a librerie dedicate, a fornire un interfaccia ai dispositivi di input su ps2, come mouse e tastiera.

VesaDriver
----------
`VesaDriver` é un server di livello driver, provvede a impostare la risoluzione grafica più simile a quella fornita tramite messaggio tra quelle disponibili nel bios

TimeDriver
----------
`TimeDriver` é un altro server di livello driver, provvede, tramite messaggi e a librerie dedicate, a fornire la data e l'ora leggendo da RTC