# Thread & process structure documentation
:toc: left
:last-update-label!:
:source-highlighter: prettify 
include::../common/homelink.adoc[]

:numbered:
[[Thread]]
Thread
-------
Un thread è un singolo flusso di esecuzione di codice. La documentazione contiene informazioni sul loro stato corrente e la loro configurazione. 
Tutti i thread vengono eseguiti esclusivamente in userspace, non ci sono thread in esecuzione nel kernelspace per motivi architetturali.

Ogni thread ha un identificatore unico di tipo `Tid`. Questo id può essere ottenuto all'interno del codice userspace tramite la chiamata `<<libapi#GetTid,GetTid>>`.

Ogni thread ha i suoi personali stack di memoria userspace e kernelspace. Guarda la sezione <<memory#Stacks, Stacks>> nella documentazione inerente.

Tipi di Thread
--------------
Le seguenti costanti denotano i tipi di thread.
[options="header"]
|==========================================================
| Costante			| Descrizione
| THREAD_TYPE_MAIN	    | Thread principale del processo
| THREAD_TYPE_SUB		| Sotto-thread del processo
| THREAD_TYPE_VM86	    | Thread VM86
|==========================================================



Creazione Thread
----------------
Per creare un thread va usata la chiamata di sistema `<<libapi#CreateThread,CreateThread>>`.
La funzione va fornita come puntatore alla funzione che il thread andrà a eseguire.
Il nome della funzione è usato come entry del thread.
Le variazioni apportate dal thread possono essere condivise tramite un puntatore.

Un semplice esempio come questo mostra come creare un thread che incrementa una variabile:

[source,c]
---------------------------------------------------
#include <eva.h>
#include <iostream>

// function that contain thread body
void counterThread(int *counter) 
{
    for (;;)
        (*counter)++;
}

// main of application
int main(int argc, char *argv[]) 
{
    int counter = 0;
    CreateThreadD((void*)counterThread, &counter);

    while (true)
    {
        Sleep(1000);
        std::cout << "The counter is: " << counter << std::endl;
    }
}
---------------------------------------------------

Internamente
------------

Internamente un thread viene creato tramite due chiamate di sistema, la prima è `SYSCALL_GET_THREAD_ENTRY`, che restituisce un costrutto intermedio per il thread, ovvero la sua parte iniziale e la parte finale, al suo centro il kernel interpone, tramite la chiamata `SYSCALL_CREATE_THREAD`, la funzione passata alla chiamata `<<libapi#CreateThread,CreateThread>>`, e vi passa gli eventuali dati.

L'intera procedura viene fatto per evitare che il kernel debba modificare lo stack user per impilarci i dati necessari, ma così facendo il tutto avviene in maniera automatica tramite le chiamate.


Exiting a thread
----------------
Un thread viene automaticamente terminato e deallocato non appena termina il codice che deve eseguire.
Quanto il thread main muore, viene terminato tutto il <<Processi,processo>> e i sotto thread.

[[Processi]]
Processi
--------
Un processo è un contenitore di uno o più thread e di informazioni che
sono comuni per tutti i thread. Ogni processo ha un thread principale e può avere più thread figli.
Un processo non ha un id proprio, ma possiede lo stesso `Tid` del thread main.



[[SecurityLevels]]
Security Levels
---------------
Quando viene creato un processo, il livello di sicurezza, viene usato per determinare il livello di permessi che thread del processo possiede.
Il livello di sicurezza viene applicato ai thread quando vengono creati.

Existing security levels
------------------------
Le seguenti costanti del tipo `SecurityLevel` descrivono i diversi livelli di sicurezza
[options="header"]
|==========================================================
| Costante					| Descrizione
| `SECURITY_LEVEL_APPLICATION`  | Nessun permesso particolare.
| `SECURITY_LEVEL_DRIVER`		| Ha permessi di I/O di livello 3 (può usare `out` e
	`in` per accedere alle porte di I/O della CPU). Inoltre viene permesso l'uso delle chiamate di sistema di livello driver.
| `SECURITY_LEVEL_KERNEL`		| Permessi massimi, viene applicato solo allo spawner.
|==========================================================


