= MeetiX OS Project Documentation [Italiano]
Marco Cicognani <marco.cicognani@btstore.com> Damiano Morandi <damianomorandi101@gmail.com>
v1.0:

About
-----
Benvenuto nella documentazione italiana di MeetiX OS!

MeetiX OS è un sistema operativo per piattaforme x86.
Cominciato come fork del Mudstorm OS e successivamente del Ghost Kernel,
MeetiX OS è ora un sistema operativo nuovo e indipendete.
Abbiamo pesantemente modificato il Ghost kernel aggiungendo features presenti nelle versioni precedenti del kernel e il risultato è stato EvangelionNG.

I contenuti di questa documentazione sono divisi in sezione per ogni parte del sistema.
dentro ogni sezione è presente un link per tornare alla home e un indice per scorrere i capitoli di ogni sezione.

* *<<EvangelionNG#, Kernel>>* - Contiene documentazione su EvangelionNG, il kernel di MeetiX OS.
* *<<libapi#,EvaApi>>* - Documentazione sulle primitive del Kernel EvangelionNG
* *<<libc#,libc>>* - Documentazione sul port della libreria C
* *<<libuser#, MXuser>>* - Documentazione della libreria home-made per MeetiX OS
* *<<ramdisk-format#,Ramdisk>>* - Documentazione sulla gestione e sulla creazione del ramdisk